services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
    restart: unless-stopped
    networks:
      - payment-processor

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r-api-1
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    restart: unless-stopped
    networks:
      - payment-processor

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r-api-2
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    restart: unless-stopped
    networks:
      - payment-processor

  redis:
    image: redis:7-alpine
    container_name: redis
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"
    restart: unless-stopped
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true