services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r-api
    ports:
      - "9999:9999"
    mem_limit: 250m
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    mem_limit: 80m